# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Saeed Gholami Shahbandi
tagline:          "Personal Website"
description:      ''
url:              https://saeed.im
baseurl:          /

author:
  name:           'Saeed Gholami Shahbandi'
  url:            https://twitter.com/saeedghsh

paginate:         5

# Custom vars
version:          0.0.1-dev

github:
  repo:           https://github.com/saeedghsh/saeedghsh.github.io

gems:
  - jekyll-sitemap

exclude: [vendor]

500px_consumer_key_file: 500pxAPIconsumerkey